site:
  title: Tracer Spec Workflow
  start_page: tracer-spec::index.adoc
content:
  sources:
    - url: .
      start_path: examples/tracer
      branches: HEAD
antora:
  extensions:
    - require: antora-tracer/antora-extension
      config:
        path: traceability.yml
        generateMatrices: true
        generateCoverage: true
ui:
  bundle:
    url: https://github.com/opendevise/antora-ui-default/releases/download/v2.1.2/ui-bundle-2.1.2.zip
output:
  dir: ./build/site
