site:
  title: {{title}}
  start_page: {{name}}:specs:index.adoc
content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD
antora:
  extensions:
    - require: '@antora-tracer/core/antora-extension'
      config:
        configPath: traceability.yml
        generateMatrices: true
        generateCoverage: true
ui:
  bundle:
    url: https://github.com/opendevise/antora-ui-default/releases/download/v2.1.2/ui-bundle-2.1.2.zip
output:
  dir: ./build/site
